### PR TITLE
Sponsors page

### LINKED ISSUE #10: Add sponsors section
For now, we decided to have same peers as https://react-finland.fi does.

### PR DESCRIPTION
**Pull request by okonet**
Closes #10

### CODE REVIEW

**Comment by okonet** [comment]
@ryyppy any idea what the compiler is trying to tell me? 

```
  Warning number 8
  /Users/okonet/Projects/reason-conf/src/components/sponsorTier.re 11:7-16:7
  
   9 ┆ render: _self => {
  10 ┆   let className =
  11 ┆     switch tier.id {
  12 ┆     | "main" => style##main
   . ┆ ...
  15 ┆     | "" => style##root
  16 ┆     };
  17 ┆   let href = "mailto:hi@reason-conf.com?subject=Sponsoring: " ++ tier.
       name;
  18 ┆   <a href className>
  
  You forgot to handle a possible value here, for example: 
"*"
```

**Comment by ryyppy** [comment]
Your switch is not exhaustive.
Instead of `| "" =>` you probably wan t`| _ => style##root` which is a default case for all unmatched cases.

Btw, your `href` string is not unicode compatible, you will most likely need to do `{j|mailto: hi@reason-conf.com?subject=Sponsoring: $tier|j}`

**Comment by okonet** [comment]
@ryyppy it didn't fix the build, though.

```
3:06:56 PM: error Building static HTML for pages failed
3:06:56 PM: See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
3:06:56 PM:   20 |  * primarily useful idiomatically for overridable function endpoints which
3:06:56 PM:   21 |  * always need to be callable, since JS lacks a null-call idiom ala Cocoa.
3:06:56 PM: > 22 |  */
3:06:56 PM:      | ^
3:06:56 PM:   23 | var emptyFunction = function emptyFunction() {};
3:06:56 PM:   24 |
3:06:56 PM:   25 | emptyFunction.thatReturns = makeEmptyFunction;
3:06:56 PM: 
3:06:56 PM:   WebpackError: 
```

**Comment by nikgraf** [comment]
@okonet can we add a section what we plan to spend the money on? I know some potential sponsors asked for that.

**Comment by okonet** [comment]
We can. What should be added there?

**Comment by nikgraf** [comment]
@okonet basically

What is the money used for?

- Catering
- Location
- Accommodation and travel costs
- Professional video recordings
- Tax Accountant
- Lanyards

**Pull request merged**
